### ISSUE TITLE
[Epic] Quadratic Voting

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/zengo#64]
- [ ] Function to distribute voting points automatically
- [ ] update Voting points individually
- [ ] Voting process and duration
- [ ] conclude Quadratic Voting
- [ ] Distribute Funds from Quadratic Voting
